#!/usr/bin/env bash

set -e
set -x

CURRENT_BRANCH="master"

function split()
{
    SHA1=`./lib/splitsh-lite --prefix=$1`
    git push $2 "$SHA1:refs/heads/$CURRENT_BRANCH" -f
}

function remote()
{
    git remote add $1 $2 || true
}

git pull origin $CURRENT_BRANCH

remote contracts-injection git@github.com:silvermoon-framework/contracts-injection.git

remote exception git@github.com:silvermoon-framework/exception.git
remote injection git@github.com:silvermoon-framework/injection.git

split 'packages/contracts/contracts-injection' contracts-injection

split 'packages/component/exception' exception
split 'packages/component/injection' injection

